
package com.itheima.bos.crm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CustomerService", targetNamespace = "http://service.crm.bos.itheima.com/")
@XmlSeeAlso({
})
public interface CustomerService {


    /**
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.SaveResponse")
    public void save(
            @WebParam(name = "arg0", targetNamespace = "")
                    Customer arg0);

    /**
     * @return returns java.util.List<com.itheima.bos.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateCustomers", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.UpdateCustomers")
    @ResponseWrapper(localName = "updateCustomersResponse", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.UpdateCustomersResponse")
    public void updateCustomers(
            @WebParam(name = "arg0", targetNamespace = "")
                    List<Integer> arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

    /**
     * @param arg0
     * @return returns java.util.List<com.itheima.bos.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomersHasAssociation", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.FindCustomersHasAssociation")
    @ResponseWrapper(localName = "findCustomersHasAssociationResponse", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.FindCustomersHasAssociationResponse")
    public List<Customer> findCustomersHasAssociation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @return returns java.util.List<com.itheima.bos.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomersNotAssociation", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.FindCustomersNotAssociation")
    @ResponseWrapper(localName = "findCustomersNotAssociationResponse", targetNamespace = "http://service.crm.bos.itheima.com/", className = "com.itheima.bos.crm.service.FindCustomersNotAssociationResponse")
    public List<Customer> findCustomersNotAssociation();

}
